# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Topic.create(name: 'lost', description: 'TV Series')
Hint.create(topic_id: 1, description: "What did you think the Smoke Monster was when you first saw it?", thumbnail_url: "topics/lost/1.jpg")
Hint.create(topic_id: 1, description: "Are you more like Jack Shepherd or John Locke('man of science' or 'man of faith')?", thumbnail_url: "topics/lost/2.jpg")
Hint.create(topic_id: 1, description: "Did you like how the series ended?", thumbnail_url: "topics/lost/3.jpg")
Hint.create(topic_id: 1, description: "Who was the cooler character: Kate or Sawyer", thumbnail_url: "topics/lost/4.jpg")
Hint.create(topic_id: 1, description: "Don't you wish you could be friends with Hurley?", thumbnail_url: "topics/lost/5.jpg")
Hint.create(topic_id: 1, description: "Did you like that time traveling was part of the show?", thumbnail_url: "topics/lost/6.jpg")
Hint.create(topic_id: 1, description: "Do you have a favorite moment in the show?", thumbnail_url: "topics/lost/7.jpg")
Hint.create(topic_id: 1, description: "Are there any other TV shows as good as LOST?", thumbnail_url: "topics/lost/8.jpg")

Topic.create(name: 'batman', description: 'Movies')
Hint.create(topic_id: 2, description: "Do you think Bane is a better villain than the Joker?", thumbnail_url: "topics/batman/1.jpg")
Hint.create(topic_id: 2, description: "Do you think Anne Hathaway plays well the role of Catwoman?", thumbnail_url: "topics/batman/2.jpg")
Hint.create(topic_id: 2, description: "Would you prefer to drive the Batmobile, the Bat Cycle or the Bat Wing?", thumbnail_url: "topics/batman/3.jpg")
Hint.create(topic_id: 2, description: "Who is cooler: Lucius Fox (Morgan Freeman) or Alfred Pennyworth (Michael Caine)", thumbnail_url: "topics/batman/4.jpg")
Hint.create(topic_id: 2, description: "Which Batman gadget has been the coolest in the series?", thumbnail_url: "topics/batman/5.jpg")
Hint.create(topic_id: 2, description: "What would you do to beat Batman?", thumbnail_url: "topics/batman/6.jpg")
Hint.create(topic_id: 2, description: "Who  would win in a fight where all gadgets are allowed: Batman or Iron Man?", thumbnail_url: "topics/batman/7.jpg")

Topic.create(name: 'avatar', description: 'Movies')
Hint.create(topic_id: 3, description: "What is your favorite creature on the planet Pandora?", thumbnail_url: "topics/avatar/1.jpg")
Hint.create(topic_id: 3, description: "Would you ever volunteer to explore Pandora?", thumbnail_url: "topics/avatar/2.jpg")
Hint.create(topic_id: 3, description: "Would you want to live in Home Tree?", thumbnail_url: "topics/avatar/3.jpg")
Hint.create(topic_id: 3, description: "What do you think is going to happen in the sequel to Avatar?", thumbnail_url: "topics/avatar/4.jpg")
Hint.create(topic_id: 3, description: "Do you think there is a planet out there with species like the Navi?", thumbnail_url: "topics/avatar/5.jpg")
Hint.create(topic_id: 3, description: "Would you want to fly like Jake on this creature?", thumbnail_url: "topics/avatar/6.jpg")
Hint.create(topic_id: 3, description: "How many times did you see Avatar when it was in theatres?", thumbnail_url: "topics/avatar/7.jpg")
Hint.create(topic_id: 3, description: "Did you see Avatar in 3-D?", thumbnail_url: "topics/avatar/8.jpg")

Topic.create(name: 'up', description: 'Movies')
Hint.create(topic_id: 4, description: "Which was your favorite: Kenvin (the bird) or Dug (the dog)?", thumbnail_url: "topics/up/1.jpg")
Hint.create(topic_id: 4, description: "What's your favorite moment in the movie?", thumbnail_url: "topics/up/2.jpg")
Hint.create(topic_id: 4, description: "Be honest: did you cry when you saw the Carl and Ellie scene?", thumbnail_url: "topics/up/3.jpg")
Hint.create(topic_id: 4, description: "Is Up the best movie that Pixar has made?", thumbnail_url: "topics/up/4.jpg")
Hint.create(topic_id: 4, description: "Where is your Paradise Falls (where you would fly in your adventure)?", thumbnail_url: "topics/up/5.jpg")
Hint.create(topic_id: 4, description: "Do you believe that exotic undiscovered animals like Kevin really exist?", thumbnail_url: "topics/up/6.jpg")
Hint.create(topic_id: 4, description: "Do you know anyone like Carl Fredericksen?", thumbnail_url: "topics/up/7.jpg")
Hint.create(topic_id: 4, description: "Are there any programs like the Wilderness Explorers where you live?", thumbnail_url: "topics/up/8.jpg")

Topic.create(name: 'mario_kart', description: 'Videogame')
Hint.create(topic_id: 5, description: "Do you remember where and when do you first played MarioKart?", thumbnail_url: "topics/mario_kart/1.jpg")
Hint.create(topic_id: 5, description: "Which character did you always pick?", thumbnail_url: "topics/mario_kart/2.jpg")
Hint.create(topic_id: 5, description: "What was better: strength or speed?", thumbnail_url: "topics/mario_kart/3.jpg")
Hint.create(topic_id: 5, description: "Was Block Fort your favorite level in Battle Mode?", thumbnail_url: "topics/mario_kart/4.jpg")
Hint.create(topic_id: 5, description: "What was the hardest level in the game?", thumbnail_url: "topics/mario_kart/5.jpg")
Hint.create(topic_id: 5, description: "Which did you prefer: the red shells or the green shells?", thumbnail_url: "topics/mario_kart/6.jpg")
Hint.create(topic_id: 5, description: "How annoying was it when someone shocked you with the lightning?", thumbnail_url: "topics/mario_kart/7.jpg")
Hint.create(topic_id: 5, description: "On Koopa Troopa Beach, did you use the secret ramp behind the waterfall?", thumbnail_url: "topics/mario_kart/8.jpg")

Topic.create(name: 'game_of_thrones', description: 'TV Series')
Hint.create(topic_id: 6, description: "Tyrion Lannister: mad man or genius?", thumbnail_url: "topics/game_of_thrones/1.jpg")
Hint.create(topic_id: 6, description: "Who do you think Daenerys Targaryen will attack first with her dragons?", thumbnail_url: "topics/game_of_thrones/2.jpg")
Hint.create(topic_id: 6, description: "Which character in the show would you want to be?", thumbnail_url: "topics/game_of_thrones/3.jpg")
Hint.create(topic_id: 6, description: "Who is more annoying? Theon Greyjoy or King Joffrey?", thumbnail_url: "topics/game_of_thrones/4.jpg")
Hint.create(topic_id: 6, description: "Which episode has been your favorite so far?", thumbnail_url: "topics/game_of_thrones/5.jpg")
Hint.create(topic_id: 6, description: "Which would win in a battle: the White Walkers or the dragons?", thumbnail_url: "topics/game_of_thrones/6.jpg")
Hint.create(topic_id: 6, description: "Who would you rather fight for: Robb Stark or Tywin Lannister?", thumbnail_url: "topics/game_of_thrones/7.jpg")
Hint.create(topic_id: 6, description: "Who are the most rutheless: the Dothraki or the pirates of the Iron Islands?", thumbnail_url: "topics/game_of_thrones/8.jpg")

Topic.create(name: 'steve_jobs', description: 'Character')
Hint.create(topic_id: 7, description: "Which invention of Steve Jobs do you think was the most important?", thumbnail_url: "topics/steve_jobs/1.jpg")
Hint.create(topic_id: 7, description: "What was your first Apple product (or which one do you want)?", thumbnail_url: "topics/steve_jobs/2.jpg")
Hint.create(topic_id: 7, description: "Would you want to hang out with Steve Jobs?", thumbnail_url: "topics/steve_jobs/3.jpg")
Hint.create(topic_id: 7, description: "In 100 years how will society look back on Steve Jobs?", thumbnail_url: "topics/steve_jobs/4.jpg")
Hint.create(topic_id: 7, description: "Would you want to work for Steve Jobs?", thumbnail_url: "topics/steve_jobs/5.jpg")
Hint.create(topic_id: 7, description: "Was Steve Jobs the closest thing to Iron Man that the world had?", thumbnail_url: "topics/steve_jobs/6.jpg")
Hint.create(topic_id: 7, description: "What industry do you wish Steve Jobs had tried to revolutionize next?", thumbnail_url: "topics/steve_jobs/7.jpg")
Hint.create(topic_id: 7, description: "Which device do you think was more important: the iPod or the Gameboy?", thumbnail_url: "topics/steve_jobs/8.jpg")

Topic.create(name: 'the_simpsons', description: 'TV Series')
Hint.create(topic_id: 8, description: "Who do you like better: Homer or Bart?", thumbnail_url: "topics/the_simpsons/1.jpg")
Hint.create(topic_id: 8, description: "Do you know anyone like Ned Flanders?", thumbnail_url: "topics/the_simpsons/3.jpg")
Hint.create(topic_id: 8, description: "How often do you watch the Simpsons?", thumbnail_url: "topics/the_simpsons/4.jpg")
Hint.create(topic_id: 8, description: "Is your personality more like Bart or Lisa?", thumbnail_url: "topics/the_simpsons/5.jpg")
Hint.create(topic_id: 8, description: "Is it even possible to have hair like Marge Simpson's?", thumbnail_url: "topics/the_simpsons/6.jpg")
Hint.create(topic_id: 8, description: "What is your favorite episode of the Simpsons?", thumbnail_url: "topics/the_simpsons/7.jpg")
Hint.create(topic_id: 8, description: "Who is funnier? Grandrpa Simpson or Ralph Wiggum?", thumbnail_url: "topics/the_simpsons/8.jpg")

Topic.create(name: 'harry_potter', description: 'Movies')
Hint.create(topic_id: 9, description: "Which Harry Potter book was your favorite?", thumbnail_url: "topics/harry_potter/1.jpg")
Hint.create(topic_id: 9, description: "In the end who was the coolest: Albus Dumbledore or Severus Snape?", thumbnail_url: "topics/harry_potter/3.jpg")
Hint.create(topic_id: 9, description: "Which did you prefer: the movies or the books?", thumbnail_url: "topics/harry_potter/4.jpg")
Hint.create(topic_id: 9, description: "What animal would your Patronus be?", thumbnail_url: "topics/harry_potter/5.jpg")
Hint.create(topic_id: 9, description: "Who would you rather have as your friend: Ron or Hermione?", thumbnail_url: "topics/harry_potter/6.jpg")
Hint.create(topic_id: 9, description: "Which character should have his own book series written about him?", thumbnail_url: "topics/harry_potter/7.jpg")
Hint.create(topic_id: 9, description: "Which house would you have belonged to at Hogwarts?", thumbnail_url: "topics/harry_potter/8.jpg")

Language.create(name: 'spanish', thumbnail_url: 'languages/spanish.png')
Language.create(name: 'english', thumbnail_url: 'languages/english.png')
Language.create(name: 'portuguese', thumbnail_url: 'languages/portuguese.png')
Language.create(name: 'chinese', thumbnail_url: 'languages/chinese.png')
Language.create(name: 'french', thumbnail_url: 'languages/french.png')
Language.create(name: 'japanese', thumbnail_url: 'languages/japanese.png')
