#!/bin/env ruby
# encoding: utf-8

Topic.create(name: 'apple', description: 'Products', thumbnail_url: 'topics/apple/apple.gif', :enabled => true)
Hint.create(language_id: 1, topic_id: 1, description: "Everyone loves Apple! Click next for help on topics!", thumbnail_url: "topics/apple/1.gif")
Hint.create(language_id: 1, topic_id: 1, description: "What was your first Apple product (or what do you want it to be)?", thumbnail_url: "topics/apple/2.gif")
Hint.create(language_id: 1, topic_id: 1, description: "What industry do you think Apple should disrupt next?", thumbnail_url: "topics/apple/3.gif")
Hint.create(language_id: 1, topic_id: 1, description: "Apple or Android: which is better?", thumbnail_url: "topics/apple/4.gif")
Hint.create(language_id: 1, topic_id: 1, description: "Describe the kind of company you would want to start.", thumbnail_url: "topics/apple/5.gif")
Hint.create(language_id: 1, topic_id: 1, description: "In 100 years, how will the world look back on Steve Jobs?", thumbnail_url: "topics/apple/6.gif")
Hint.create(language_id: 1, topic_id: 1, description: "iPad or iPhone: which one would you want more?", thumbnail_url: "topics/apple/7.gif")

Hint.create(language_id: 2, topic_id: 1, description: "Todo mundo adora a Apple! Presiona siguiente para ayuda con el tema", thumbnail_url: "topics/apple/1.gif")
Hint.create(language_id: 2, topic_id: 1, description: "¿Cuál fue tu primer producto Apple (o cuál te gustaría que fuera)?", thumbnail_url: "topics/apple/2.gif")
Hint.create(language_id: 2, topic_id: 1, description: "¿Qué otra industria te gustaría que Apple innovara?", thumbnail_url: "topics/apple/3.gif")
Hint.create(language_id: 2, topic_id: 1, description: "iOS o Android: ¿cuál crees que es mejor?", thumbnail_url: "topics/apple/4.gif")
Hint.create(language_id: 2, topic_id: 1, description: "¿Qué harías si fueras el dueño de Apple?", thumbnail_url: "topics/apple/5.gif")
Hint.create(language_id: 2, topic_id: 1, description: "En 100 años, ¿cómo crees que el mundo recuerde a Steve Jobs?", thumbnail_url: "topics/apple/6.gif")
Hint.create(language_id: 2, topic_id: 1, description: "iPad o iPhone: ¿cuál te gustaría tener más?", thumbnail_url: "topics/apple/7.gif")

Topic.create(name: 'avatar', description: 'Movies', thumbnail_url: 'topics/avatar/avatar.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 2, description: "What is your favorite creature on the planet Pandora?", thumbnail_url: "topics/avatar/1.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "Would you ever volunteer to explore Pandora?", thumbnail_url: "topics/avatar/2.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "Would you want to live in Home Tree?", thumbnail_url: "topics/avatar/3.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "What do you think is going to happen in the sequel to Avatar?", thumbnail_url: "topics/avatar/4.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "Do you think there is a planet out there with species like the Navi?", thumbnail_url: "topics/avatar/5.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "Would you want to fly like Jake on this creature?", thumbnail_url: "topics/avatar/6.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "How many times did you see Avatar when it was in theatres?", thumbnail_url: "topics/avatar/7.jpg")
Hint.create(language_id: 1, topic_id: 2, description: "Did you see Avatar in 3-D?", thumbnail_url: "topics/avatar/8.jpg")

Topic.create(name: 'beatles', description: 'Music', thumbnail_url: 'topics/beatles/beatles.gif', :enabled => true)
Hint.create(language_id: 1, topic_id: 3, description: "Sweet, the Beatles! Click next for topics!", thumbnail_url: "topics/beatles/1.gif")
Hint.create(language_id: 1, topic_id: 3, description: "Paul, John, George, or Ringo: who was the most important?", thumbnail_url: "topics/beatles/2.gif")
Hint.create(language_id: 1, topic_id: 3, description: "Beatles or Star Wars: which had a more profound impact?", thumbnail_url: "topics/beatles/3.gif")
Hint.create(language_id: 1, topic_id: 3, description: "Guess when this photo was taken?", thumbnail_url: "topics/beatles/4.gif")
Hint.create(language_id: 1, topic_id: 3, description: "Besides the Beatles (and Muhammad Ali), who is your favorite celebrity from the 1960s and 1970s?", thumbnail_url: "topics/beatles/5.gif")
Hint.create(language_id: 1, topic_id: 3, description: "This old man was accidentally on the Abbey Road cover. Whoa…", thumbnail_url: "topics/beatles/6.gif")
Hint.create(language_id: 1, topic_id: 3, description: "My favorite Beatles song is ... because ...", thumbnail_url: "topics/beatles/7.gif")

Hint.create(language_id: 2, topic_id: 3, description: "¡Excelente, los Beatles! Presiona siguiente para obtener un tema", thumbnail_url: "topics/beatles/1.gif")
Hint.create(language_id: 2, topic_id: 3, description: "Paul, John, George, o Ringo: ¿quién fue el más importante?", thumbnail_url: "topics/beatles/2.gif")
Hint.create(language_id: 2, topic_id: 3, description: "Beatles o Star Wars: ¿qué crees que ha tenido un impacto más profundo?", thumbnail_url: "topics/beatles/3.gif")
Hint.create(language_id: 2, topic_id: 3, description: "¿Cuándo crees que se tomó esta foto?", thumbnail_url: "topics/beatles/4.gif")
Hint.create(language_id: 2, topic_id: 3, description: "Aparte de los Beatles (y Muhammad Ali), ¿quién es tu celebridad favorita de los 60's y 70's?", thumbnail_url: "topics/beatles/5.gif")
Hint.create(language_id: 2, topic_id: 3, description: "Este señor salió por accidente en la portada de Abbey Road... ¿sabes historias similares?", thumbnail_url: "topics/beatles/6.gif")
Hint.create(language_id: 2, topic_id: 3, description: "Mi canción favorita de los Beatles es ... debido a ...", thumbnail_url: "topics/beatles/7.gif")

Topic.create(name: 'food', description: 'Food', thumbnail_url: 'topics/food/food.gif', :enabled => true)
Hint.create(language_id: 1, topic_id: 4, description: "Hungry to talk about food? Click next for help on topics.", thumbnail_url: "topics/food/1.gif")
Hint.create(language_id: 1, topic_id: 4, description: "They say every culture in the world has it's own type of bread. Describe bread in your country.", thumbnail_url: "topics/food/2.gif")
Hint.create(language_id: 1, topic_id: 4, description: "Are you a breakfast, lunch, or dinner kind of person?", thumbnail_url: "topics/food/3.gif")
Hint.create(language_id: 1, topic_id: 4, description: "What's the craziest food you've ever eaten?", thumbnail_url: "topics/food/4.gif")
Hint.create(language_id: 1, topic_id: 4, description: "Bacon milkshake. Thoughts?", thumbnail_url: "topics/food/5.gif")
Hint.create(language_id: 1, topic_id: 4, description: "What is your favorite dessert?", thumbnail_url: "topics/food/6.gif")
Hint.create(language_id: 1, topic_id: 4, description: "Beer or wine (or neither) with your dinner?", thumbnail_url: "topics/food/7.gif")

Hint.create(language_id: 2, topic_id: 4, description: "¿Estás hambriento? Presiona siguiente para ver temas relacionados con comida", thumbnail_url: "topics/food/1.gif")
Hint.create(language_id: 2, topic_id: 4, description: "Se sabe que cada cultura en el mundo tiene su propio tipo de pan. ¿Cuál es el pan de tu zona?", thumbnail_url: "topics/food/2.gif")
Hint.create(language_id: 2, topic_id: 4, description: "¿Qué comida disfrutas más? ¿Desayuno, comida o cena?", thumbnail_url: "topics/food/3.gif")
Hint.create(language_id: 2, topic_id: 4, description: "¿Cuál es el platillo más extraño que has comido?", thumbnail_url: "topics/food/4.gif")
Hint.create(language_id: 2, topic_id: 4, description: "Malteada de tocino. ¿Qué te hace pensar?", thumbnail_url: "topics/food/5.gif")
Hint.create(language_id: 2, topic_id: 4, description: "¿Cuál es tu postre favorito?", thumbnail_url: "topics/food/6.gif")
Hint.create(language_id: 2, topic_id: 4, description: "¿Prefieres cerveza o vino (o ninguno de los dos), para acompañar tu cena?", thumbnail_url: "topics/food/7.gif")

Topic.create(name: 'game_of_thrones', description: 'TV Series', thumbnail_url: 'topics/game_of_thrones/game_of_thrones.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 5, description: "Tyrion Lannister: mad man or genius?", thumbnail_url: "topics/game_of_thrones/1.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Who do you think Daenerys Targaryen will attack first with her dragons?", thumbnail_url: "topics/game_of_thrones/2.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Which character in the show would you want to be?", thumbnail_url: "topics/game_of_thrones/3.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Who is more annoying? Theon Greyjoy or King Joffrey?", thumbnail_url: "topics/game_of_thrones/4.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Which episode has been your favorite so far?", thumbnail_url: "topics/game_of_thrones/5.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Which would win in a battle: the White Walkers or the dragons?", thumbnail_url: "topics/game_of_thrones/6.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Who would you rather fight for: Robb Stark or Tywin Lannister?", thumbnail_url: "topics/game_of_thrones/7.jpg")
Hint.create(language_id: 1, topic_id: 5, description: "Who are the most rutheless: the Dothraki or the pirates of the Iron Islands?", thumbnail_url: "topics/game_of_thrones/8.jpg")

Topic.create(name: 'harry_potter', description: 'Movies', thumbnail_url: 'topics/harry_potter/harry_potter.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 6, description: "Which Harry Potter book was your favorite?", thumbnail_url: "topics/harry_potter/1.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "In the end who was the coolest: Albus Dumbledore or Severus Snape?", thumbnail_url: "topics/harry_potter/3.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "Which did you prefer: the movies or the books?", thumbnail_url: "topics/harry_potter/4.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "What animal would your Patronus be?", thumbnail_url: "topics/harry_potter/5.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "Who would you rather have as your friend: Ron or Hermione?", thumbnail_url: "topics/harry_potter/6.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "Which character should have his own book series written about him?", thumbnail_url: "topics/harry_potter/7.jpg")
Hint.create(language_id: 1, topic_id: 6, description: "Which house would you have belonged to at Hogwarts?", thumbnail_url: "topics/harry_potter/8.jpg")

Topic.create(name: 'mario_kart', description: 'Videogame', thumbnail_url: 'topics/mario_kart/mario_kart.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 7, description: "Do you remember where and when do you first played MarioKart?", thumbnail_url: "topics/mario_kart/1.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "Which character did you always pick?", thumbnail_url: "topics/mario_kart/2.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "What was better: strength or speed?", thumbnail_url: "topics/mario_kart/3.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "Was Block Fort your favorite level in Battle Mode?", thumbnail_url: "topics/mario_kart/4.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "What was the hardest level in the game?", thumbnail_url: "topics/mario_kart/5.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "Which did you prefer: the red shells or the green shells?", thumbnail_url: "topics/mario_kart/6.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "How annoying was it when someone shocked you with the lightning?", thumbnail_url: "topics/mario_kart/7.jpg")
Hint.create(language_id: 1, topic_id: 7, description: "On Koopa Troopa Beach, did you use the secret ramp behind the waterfall?", thumbnail_url: "topics/mario_kart/8.jpg")

Topic.create(name: 'michael_jackson', description: 'Music', thumbnail_url: 'topics/michael_jackson/michael_jackson.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 8, description: "", thumbnail_url: "topics/michael_jackson/1.jpg")
Hint.create(language_id: 1, topic_id: 8, description: "", thumbnail_url: "topics/michael_jackson/2.jpg")
Hint.create(language_id: 1, topic_id: 8, description: "", thumbnail_url: "topics/michael_jackson/3.jpg")
Hint.create(language_id: 1, topic_id: 8, description: "", thumbnail_url: "topics/michael_jackson/4.jpg")
Hint.create(language_id: 1, topic_id: 8, description: "", thumbnail_url: "topics/michael_jackson/5.jpg")

Topic.create(name: 'michael_jordan', description: 'Sports', thumbnail_url: 'topics/michael_jordan/michael_jordan.gif', :enabled => false)

Topic.create(name: 'nyc', description: 'World', thumbnail_url: 'topics/nyc/nyc.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 10, description: "", thumbnail_url: "topics/nyc/1.jpg")
Hint.create(language_id: 1, topic_id: 10, description: "", thumbnail_url: "topics/nyc/2.jpg")
Hint.create(language_id: 1, topic_id: 10, description: "", thumbnail_url: "topics/nyc/3.jpg")
Hint.create(language_id: 1, topic_id: 10, description: "", thumbnail_url: "topics/nyc/4.jpg")
Hint.create(language_id: 1, topic_id: 10, description: "", thumbnail_url: "topics/nyc/5.jpg")

Topic.create(name: 'olympics', description: 'World', thumbnail_url: 'topics/olympics/olympics.gif', :enabled => true)
Hint.create(language_id: 1, topic_id: 11, description: "The OLYMPICS! Intense! Click next if you need a topic!", thumbnail_url: "topics/olympics/1.gif")
Hint.create(language_id: 1, topic_id: 11, description: "Which sport would you want to compete in most?", thumbnail_url: "topics/olympics/2.gif")
Hint.create(language_id: 1, topic_id: 11, description: "How have the British done in organizing the event so far? Did you like the opening ceremony?", thumbnail_url: "topics/olympics/3.gif")
Hint.create(language_id: 1, topic_id: 11, description: "Which is better: the Winter Olympics or the Summer Olympics?", thumbnail_url: "topics/olympics/4.gif")
Hint.create(language_id: 1, topic_id: 11, description: "Have the Olympics become too commercialized?", thumbnail_url: "topics/olympics/5.gif")
Hint.create(language_id: 1, topic_id: 11, description: "True or False: What the Olympics means to Americans", thumbnail_url: "topics/olympics/6.gif")
Hint.create(language_id: 1, topic_id: 11, description: "Do you think that Rio de Janeiro is going to be ready for the 2016 Olympics?", thumbnail_url: "topics/olympics/7.gif")

Hint.create(language_id: 2, topic_id: 11, description: "¡Las olimpiadas! ¡Intenso! Presiona siguiente si necesitas un tema", thumbnail_url: "topics/olympics/1.gif")
Hint.create(language_id: 2, topic_id: 11, description: "¿En qué actividad olímpica te gustaría competir?", thumbnail_url: "topics/olympics/2.gif")
Hint.create(language_id: 2, topic_id: 11, description: "¿Qué piensas sobre la organización del evento? ¿Te gustó la ceremonia de inauguración?", thumbnail_url: "topics/olympics/3.gif")
Hint.create(language_id: 2, topic_id: 11, description: "Qué te gusta más: ¿las olimpiadas de verano o las de invierno?", thumbnail_url: "topics/olympics/4.gif")
Hint.create(language_id: 2, topic_id: 11, description: "¿Crees que las olimpiadas se han vuelto demasiado comerciales?", thumbnail_url: "topics/olympics/5.gif")
Hint.create(language_id: 2, topic_id: 11, description: "Verdadero o falso: lo que las olimpiadas significan para Estados Unidos", thumbnail_url: "topics/olympics/6.gif")
Hint.create(language_id: 2, topic_id: 11, description: "¿Qué opinas de Rio de Janeiro para las olimpiadas del 2016?", thumbnail_url: "topics/olympics/7.gif")

Topic.create(name: 'popart', description: 'World', thumbnail_url: 'topics/popart/popart.gif', :enabled => false)

Topic.create(name: 'sustainability', description: 'World', thumbnail_url: 'topics/sustainability/sustainability.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 13, description: "", thumbnail_url: "topics/sustainability/1.jpg")
Hint.create(language_id: 1, topic_id: 13, description: "", thumbnail_url: "topics/sustainability/2.jpg")
Hint.create(language_id: 1, topic_id: 13, description: "", thumbnail_url: "topics/sustainability/3.jpg")
Hint.create(language_id: 1, topic_id: 13, description: "", thumbnail_url: "topics/sustainability/4.jpg")

Topic.create(name: 'the_simpsons', description: 'TV Series', thumbnail_url: 'topics/the_simpsons/the_simpsons.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 14, description: "Who do you like better: Homer or Bart?", thumbnail_url: "topics/the_simpsons/1.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "Do you know anyone like Ned Flanders?", thumbnail_url: "topics/the_simpsons/3.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "How often do you watch the Simpsons?", thumbnail_url: "topics/the_simpsons/4.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "Is your personality more like Bart or Lisa?", thumbnail_url: "topics/the_simpsons/5.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "Is it even possible to have hair like Marge Simpson's?", thumbnail_url: "topics/the_simpsons/6.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "What is your favorite episode of the Simpsons?", thumbnail_url: "topics/the_simpsons/7.jpg")
Hint.create(language_id: 1, topic_id: 14, description: "Who is funnier? Grandrpa Simpson or Ralph Wiggum?", thumbnail_url: "topics/the_simpsons/8.jpg")

Topic.create(name: 'up', description: 'Movies', thumbnail_url: 'topics/up/up.gif', :enabled => false)
Hint.create(language_id: 1, topic_id: 15, description: "Which was your favorite: Kenvin (the bird) or Dug (the dog)?", thumbnail_url: "topics/up/1.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "What's your favorite moment in the movie?", thumbnail_url: "topics/up/2.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Be honest: did you cry when you saw the Carl and Ellie scene?", thumbnail_url: "topics/up/3.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Is Up the best movie that Pixar has made?", thumbnail_url: "topics/up/4.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Where is your Paradise Falls (where you would fly in your adventure)?", thumbnail_url: "topics/up/5.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Do you believe that exotic undiscovered animals like Kevin really exist?", thumbnail_url: "topics/up/6.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Do you know anyone like Carl Fredericksen?", thumbnail_url: "topics/up/7.jpg")
Hint.create(language_id: 1, topic_id: 15, description: "Are there any programs like the Wilderness Explorers where you live?", thumbnail_url: "topics/up/8.jpg")

Language.create(name: 'english', thumbnail_url: 'languages/english.gif')
Language.create(name: 'spanish', thumbnail_url: 'languages/spanish.gif')
Language.create(name: 'portuguese', thumbnail_url: 'languages/portuguese.gif')
Language.create(name: 'chinese', thumbnail_url: 'languages/chinese.gif')
Language.create(name: 'french', thumbnail_url: 'languages/french.gif')
Language.create(name: 'japanese', thumbnail_url: 'languages/japanese.gif')
